# Generated by Django 3.1 on 2021-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20210420_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='abc',
            field=models.OneToOneField(null=True, on_delete=models.SET(6), to='test_app.student'),
        ),
    ]
